### ISSUE TITLE
evaluation code for group detection 

### ISSUE THREAD

**Issue by suminlee94** [RuizeHan/PAR#6]
Hi.
It seems that there isn't evaluation codes for group detection.
In the paper, you measured IoU@0.5, IoU@AUC, and Mat. IoU for group detection.
Can you share the codes for those metrics?

**Comment by RuizeHan** [comment]
We will release the evaluation codes for group detection recently.

**Comment by RuizeHan** [comment]
We will release the evaluation codes for group detection soon.
