### ISSUE TITLE
stage1 weight file

### ISSUE THREAD

**Issue by suminlee94** [RuizeHan/PAR#8]
In the guideline, it says "Stage1 model weights file and annotation files are already in ./PanoAct_source-code/data".
But, I can't find pretrained model of stage 1 in './PanoAct_source-code/data'.
Only excels and txt files exist.
Can you check it is properly uploaded?

**Comment by RuizeHan** [comment]
Yes. We updated it.

**Comment by suminlee94** [comment]
> Yes. We updated it.

Thank you for reply :)
But I still can't find weight files in the directory ./PanoAct_source-code/data'.
I only see the excels and txt files.

![캡처](https://github.com/RuizeHan/PAR/assets/41566106/105e3d01-ce69-4fc6-a274-e18cf083abbb)
