### ISSUE TITLE
no stage1 weight file yet

### ISSUE THREAD

**Issue by suminlee94** [RuizeHan/PAR#9]
> Yes. We updated it.

Thank you for reply :)
But I still can't find weight files in the directory ./PanoAct_source-code/data'.
I only see the excels and txt files.

![캡처](https://github.com/RuizeHan/PAR/assets/41566106/105e3d01-ce69-4fc6-a274-e18cf083abbb)

_Originally posted by @suminlee94 in https://github.com/RuizeHan/PAR/issues/8#issuecomment-1740344082_

**Comment by RuizeHan** [comment]
Maybe the updating on github has some delay.

**Comment by suminlee94** [comment]
> Maybe the updating on github has some delay.

If it's over 25MB, it's not uploaded

**Comment by RuizeHan** [comment]
Sorry, we re-uploaded it through Baidu Yun.
